type: v1
data_path: /home/rokymiel/Documents/ex/Colorization/val_images
batch_size: 16
model_weights_path: /home/rokymiel/Documents/ex/Colorization/main_model.pt
generator_weights_path: /home/rokymiel/Documents/ex/Colorization/generator.pt
