
hydra:
  run:
    dir: outputs/${run_name}

project_name: Colorization
run_name: seed=123_v2

lr_G: 2e-4
lr_D: 2e-4
beta1: 0.5
beta2: 0.999
lambda_L1: 100.
gan_mode: vanilla
epochs: 120
batch_size: 8
seed: 123
batch_num_to_val: 2

execute_pretrain_generator_only: False

#data_path: ... # Опционально